[Options]
UIMagnification=0.0
AlienFX=False
CaptureOutputDirectory=..\Media\Videos
AudioMasterVolume=0.175000
BinkVolume=0.7
Subtitles=0
MovieSubtitles=0
MuteOnFocusChange=0
MuteAllDeathThemes=False
HideLoginDetails=True
HideYourCharacterName=False
HideCurrentWorld=False
HideCurrentDistrict=False
HideOtherCharacterNames=False
MuteIgnoredDeathThemes=True
MuteNonFriendDeathThemes=True
DisableCreatedSongs=False

[SystemSettings]
UseVsync=False
SmoothFrameRate=False
MultiGPUCompatibility=False
ResX=1024
ResY=768
AllowFog=True
StaticDecals=False
DynamicShadows=True
;QualityBloom=True
LightEnvironmentShadows=False
BlobShadows=False
AmbientOcclusion=False
Distortion=False
;bCompressDiffuseOtherPlayerCharacterTextures=True
;bCompressDiffuseOtherPlayerVehicleTextures=True
AnisotropyAmount=1
MSAA_Amount=8
m_bGameRenderEyelashes=True
OneFrameThreadLag=True
bAllowStaticDecals=False
EnvironmentShadows=False
bAllowBlobShadows=False
HighQualityBloom=False
bTrilinearFiltering=False
VideoQuality=1
Bloom=False
Fullscreen=0
bLowQualityHealthHUD=True
TrillnearMIPFiltering=False
MaxAnisotropy=16

[IniVersion]
Regenerate=1376306551.000000
0=1730255448.000000

[Engine.Client]
DisplayGamma=4.0

[Engine.PlayerInput]
MouseSensitivity=3.4679
MarksmanshipMouseSensitivity=0.5
bEnableMouseSmoothing=False

[LoginSettings]
bUseSteamLogin=True

